### ISSUE TITLE
sample for domain responses

### ISSUE THREAD

**Issue by vavrecan** [raybellis/evldns#10]
What would be the best way to use evldns with dnsmasq in order to achieve following:
- dnsmasq uses evldns as nameserver
- if evldns can match domain with specific name it forwards A record (*.home.network -> 10.0.0.1) 
- if the name is not match, default nameserver from /etc/resolv.conf will be used 

I know you could use hosts/address feature of dnsmasq, but I would like to do custom matching later, more dynamic :+1:

**Comment by raybellis** [comment]
evldns is designed for writing bespoke authoritative servers, not as a forwarder nor recursive server.

I believe that you can make dnsmasq do what you want all by itself.

**Comment by vavrecan** [comment]
I actually need to resolve to dynamic IP, its little bit more complicated for dnsmasq

**Comment by raybellis** [comment]
OK, so if you can make dnsmasq forward all queries for `*.home.network` to an evldns server and do all other lookups itself, that could work.   You would need to ensure that the evldns server is able to return the dynamic IP address immediately without having to perform any asynchronous lookups to other databases.
