### ISSUE TITLE
bind_to_{tcp,udp}{4,6}_port can not specify address

### ISSUE THREAD

**Issue by jaredmauch** [raybellis/evldns#3]
need the ability to specify a unique address vs INADDR_ANY and pass that to bind_to_port.  This will allow running multiple processes per host on different addresses.

**Comment by jaredmauch** [comment]
http://puck.nether.net/~jared/evldns.bind_address.diff

**Comment by raybellis** [comment]
Hi Jared - a few months ago I made `bind_to_port` non-static and that will take a `struct sockaddr *`.

It's slightly more work than passing an `in_addr` or `in6_addr`, but the functionality is there.  What I do plan to add though is variants that take a `const char *ipaddr` and have that resolved automatically via `getaddrinfo()` into IPv4 or IPv6 endpoints

**Comment by raybellis** [comment]
I've made some significant changes, including the addition of `evldns_add_server_all()`, with usage:

```
evldns_add_server_all(p, "localhost", "5053", 10);
```

which uses `getaddrinfo` to bind on every allowable combination of UDP and TCP with IPv4 and IPv6.  To bind on `INADDR_ANY` just pass NULL for the hostname field.
