### ISSUE TITLE
Getting the wire request for UDP queries?

### ISSUE THREAD

**Issue by edmonds** [raybellis/evldns#4]
Hi, Ray:

I have a use case where I'd like to be able to get at the original request sent over the wire by the client, but it looks like the `.wire_request` and `.wire_reqlen` fields in `evldns_server_request` are only set for TCP connections.

It looks like it would be easy to set `req->wire_request = buffer; req->wire_reqlen = buflen;` in `evldns_udp_read_callback()`. Does that sound correct?

**Comment by raybellis** [comment]
Yes, that sounds correct, with one caveat - there'd have to be a way to prevent the `req->wire_request` call in line 555.

In TCP mode the buffer is allocated dynamically for each packet but in UDP mode it's held on the stack.  It may be better to always but it on the heap.
